# Generated by Django 2.2.7 on 2019-12-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
