# Generated by Django 2.2.7 on 2019-12-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191203_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the movie', max_length=1000),
        ),
    ]
